# Generated by Django 3.0.3 on 2020-02-15 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cameriere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Inserisci il nome', max_length=200)),
                ('cognome', models.CharField(help_text='Inserisci il cognome', max_length=200)),
                ('telefono', models.CharField(help_text='Inserisci il numero di telefono', max_length=10)),
                ('email', models.EmailField(help_text="Inserisci l'indirizzo email", max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Fornitore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ragione_sociale', models.CharField(help_text='Inserisci la ragione sociale', max_length=200)),
                ('p_Iva', models.CharField(help_text='Inserisci la partita Iva', max_length=11)),
                ('citta', models.CharField(help_text='Inserisci la citta', max_length=100)),
                ('via', models.CharField(help_text='Inserisci la via', max_length=300)),
                ('cap', models.CharField(help_text='Inserisci il CAP', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Prodotti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione_breve', models.CharField(help_text='Inserisci una descrizione breve MAX 20 caratteri', max_length=20)),
                ('descrizione_lunga', models.CharField(help_text='Inserisci una descrizione', max_length=200)),
                ('unita_di_misura', models.CharField(blank=True, choices=[('pz', 'Pezzi'), ('ps', 'Peso'), ('lt', 'Litro')], help_text="Seleziona l'unità di misura", max_length=2)),
                ('iva', models.CharField(blank=True, choices=[('4', '4 %'), ('10', '10 %'), ('21', '21 %'), ('22', '22 %')], help_text="Scegli l'IVA", max_length=2)),
                ('ean', models.CharField(help_text='Inserisci il barcode', max_length=100)),
                ('prezzo_acquisto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prezzo_vendita', models.DecimalField(decimal_places=2, max_digits=5)),
                ('id_fornitore', models.ManyToManyField(help_text='Seleziona il fornitore', to='tavoli.Fornitore')),
            ],
        ),
        migrations.CreateModel(
            name='Tavoli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_Tavolo', models.CharField(help_text='Inserisci il tavolo (es. Tavolo1', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spec_Tav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('cameriere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tavoli.Cameriere')),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tavoli.Prodotti')),
                ('tavolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tavoli.Tavoli')),
            ],
        ),
    ]
