# Generated by Django 3.0.3 on 2020-02-19 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tavoli', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spec_tav',
            name='quantita',
            field=models.IntegerField(default=1),
        ),
    ]
