# Generated by Django 3.0.3 on 2020-02-23 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tavoli', '0003_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prodotti',
            options={'ordering': ['descrizione_breve']},
        ),
    ]
