# Generated by Django 3.0.3 on 2020-02-23 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tavoli', '0004_auto_20200223_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spec_tav',
            name='quantita',
        ),
    ]
