# Generated by Django 3.0.3 on 2020-02-28 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tavoli', '0005_remove_spec_tav_quantita'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scontrino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_azz', models.CharField(max_length=4, unique=True)),
                ('num_scon', models.CharField(max_length=4)),
                ('tot', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Spec_Scon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_prodotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tavoli.Prodotti')),
                ('id_scon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tavoli.Scontrino', unique=True)),
            ],
        ),
    ]
