# Generated by Django 3.0.3 on 2020-02-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tavoli', '0006_scontrino_spec_scon'),
    ]

    operations = [
        migrations.AddField(
            model_name='scontrino',
            name='tipo_pag',
            field=models.CharField(default='pagamento', max_length=20),
        ),
    ]
