# Generated by Django 3.0.3 on 2020-02-28 19:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tavoli', '0007_scontrino_tipo_pag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Azzeramenti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_azz', models.CharField(max_length=4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='scontrino',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 2, 28, 19, 57, 17, 554402, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='spec_tav',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
