# Generated by Django 3.0.3 on 2020-02-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tavoli', '0008_auto_20200228_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scontrino',
            name='num_azz',
            field=models.CharField(max_length=4),
        ),
    ]
