# Generated by Django 3.0.3 on 2020-02-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tavoli', '0009_auto_20200228_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azzeramenti',
            name='num_azz',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='scontrino',
            name='num_azz',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='scontrino',
            name='num_scon',
            field=models.IntegerField(),
        ),
    ]
