# Generated by Django 3.0.3 on 2020-03-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tavoli', '0011_auto_20200228_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='azzeramenti',
            name='tot_giornaliero',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
